In [1]:
import pandas as pd
relationship = pd.read_csv('relationship.csv')
relationship.head(10)

   PointGap   HomeWin   Draw   AwayWin
0       -15        20     15        11
1       -14         0      2         1
2       -13         1      2         3
3       -12         0      1         2
4       -11         1      1         5
5       -10        13     12        23
6        -9         8      5        18
7        -8        14     22        46
8        -7        24     26        79
9        -6        52     52       123